### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by wearegoose** [thirdandgrove/gatsby-source-bigcommerce#2]
Hey,

Thanks for taking the time to build this. I'm having trouble getting this to work. 

I have configured as per the readme, but for some reason, it's not pulling in any data.  allBigCommerceNode is not visible is the graphiQl interface.

Do you know the best way to debug this? 

Cheers

**Comment by grantglidewell** [comment]
Sorry for the delayed response. If youre still having trouble please show me the options youre using.

**Comment by wearegoose** [comment]
No worries Grant. I got it sorted. Thank.
