### ISSUE TITLE
the plugin doesn't load past the first page

### ISSUE THREAD

**Issue by vilchesalves** [thirdandgrove/gatsby-source-bigcommerce#4]
Using the endpoint `/catalog/products?include=modifiers` causes BigCommerce to limit the API response to 10 entries and, in a store with more than 10 entries, the extra pages are never loaded.

Also, inspecting the code I noticed that the same would happen in a store with more than 50 items on the catalog.

Also, there is a bug on BC API where they cut the number of entries from 50 to 10 but they do not update the meta.pagination response. It looks like the following:

```
    "meta": {
        "pagination": {
            "total": 30,
            "count": 10,
            "per_page": 50,
            "current_page": 1,
            "total_pages": 1,
            "links": {
                "current": "?include=modifiers&page=1&limit=50"
            },
            "too_many": false
        }
    }
```

This can be solved by adding the correct limit to the API call, for example /catalog/products?include=modifiers&limit=10, in which case the response becomes:

```
    "meta": {
        "pagination": {
            "total": 30,
            "count": 10,
            "per_page": 10,
            "current_page": 1,
            "total_pages": 3,
            "links": {
                "next": "?include=modifiers&limit=10&page=2",
                "current": "?include=modifiers&limit=10&page=1"
            },
            "too_many": false
        }
    }
```

I'll try something but can't promise a fix.

Cheers!

**Comment by grantglidewell** [comment]
interesting, is it possibly the case where the bug in BC API is causing this behavior?

**Comment by vilchesalves** [comment]
> interesting, is it possibly the case where the bug in BC API is causing this behavior?

I don't think so. As far as my reading of the code goes, I couldn't find any pagination handling, so that bug would also surface on stores with more than one page of products.

My suggestion would be that it is needed to call it once, in order to know how many pages are there, then create parallel calls for the remaining pages.

**Comment by grantglidewell** [comment]
I would certainly be interested in a PR with this. There is an issue with which endpoints a user selects to pull from, so we would need to account for that somehow.

**Comment by grantglidewell** [comment]
I am also unfamiliar with the fault tolerance of ramda, Ive heard positive things about the library and dont have a problem adding it, but I would want to ensure with the referencing happening that there is proper error handling if say a call fails.

**Comment by gaufisher** [comment]
For anyone else reading this issue, this is intended behavior according to Big Commerce API Docs: 

> Sub-resources to include on a product, in a comma-separated list. If options or modifiers is used, results are limited to 10 per page.
